ssg-240304-java2/wms-justdo

- src/main/java/com/justdo/fruitfruit/NotificationMapper.java
- src/main/java/com/justdo/fruitfruit/model/DTO/NotificationDTO.java
- src/main/java/com/justdo/fruitfruit/model/service/CommonService.java
- src/main/java/com/justdo/fruitfruit/model/service/SellerService.java
- src/main/java/com/justdo/fruitfruit/view/SellerMenu.java
- src/main/resources/com/justdo/fruitfruit/NotificationMapper.xml
> #16 판매자 알림 조회

- src/main/java/com/justdo/fruitfruit/NotificationMapper.java
- src/main/java/com/justdo/fruitfruit/controller/ProductController.java
- src/main/java/com/justdo/fruitfruit/model/dao/ProductMapper.java
- src/main/java/com/justdo/fruitfruit/model/dto/CategoryDTO.java
- src/main/java/com/justdo/fruitfruit/model/dto/NotificationDTO.java
- src/main/java/com/justdo/fruitfruit/model/dto/ProductDTO.java
- src/main/java/com/justdo/fruitfruit/model/service/ProductService.java
- src/main/java/com/justdo/fruitfruit/model/service/SellerService.java
- src/main/java/com/justdo/fruitfruit/model/service/WarehouseService.java
- src/main/java/com/justdo/fruitfruit/view/ProductResultMessage.java
- src/main/java/com/justdo/fruitfruit/view/SellerMenu.java
- src/main/resources/com/justdo/fruitfruit/NotificationMapper.xml
- src/main/resources/sql/seller/ProductMapper.xml
상품 관리 view, 상품 입력 받기, 상품 status 변경, dto name 변경
> #15 Feat : 판매자 상품 관리 기능 개발

- src/main/java/com/justdo/fruitfruit/controller/CategoryController.java
- src/main/java/com/justdo/fruitfruit/controller/ProductController.java
- src/main/java/com/justdo/fruitfruit/controller/UserController.java
- src/main/java/com/justdo/fruitfruit/model/dao/CategoryMapper.java
- src/main/java/com/justdo/fruitfruit/model/dao/ProductMapper.java
- src/main/java/com/justdo/fruitfruit/model/dao/UserMapper.java
- src/main/java/com/justdo/fruitfruit/model/dto/CategoryDTO.java
- src/main/java/com/justdo/fruitfruit/model/dto/ProductDTO.java
- src/main/java/com/justdo/fruitfruit/model/dto/UserDTO.java
- src/main/java/com/justdo/fruitfruit/model/service/CategoryService.java
- src/main/java/com/justdo/fruitfruit/model/service/CommonService.java
- src/main/java/com/justdo/fruitfruit/model/service/ProductService.java
- src/main/java/com/justdo/fruitfruit/model/service/UserService.java
- src/main/java/com/justdo/fruitfruit/view/CategoryResultMessage.java
- src/main/java/com/justdo/fruitfruit/view/MainMenu.java
- src/main/java/com/justdo/fruitfruit/view/UserMenu.java
- src/main/java/com/justdo/fruitfruit/view/UserResultMessage.java
- src/main/resources/config/mybatis-config.xml
- src/main/resources/sql/seller/ProductMapper.xml
- src/main/resources/sql/user/CategoryMapper.xml
- src/main/resources/sql/user/ProductMapper.xml
- src/main/resources/sql/user/UserMapper.xml
구매자 회원 등록 기능 개발 완료했고 ,
구매자 회원 로그인 , 회원가입 기능 개발 완료 했습니다.
- 구매자 회원 입력 받기
- 입력받은 회원 데이터 테이블에 저장
- 구매자 회원으로 로그인처리
- 구매자 회원 view 생성
- 상품조회 view 생성
- 상품 전체 조회 처리
- 카테고리별 물품 조회 처리
> #17 feat: 구매자 회원기능 개발

- src/main/java/com/justdo/fruitfruit/controller/CompanyController.java
- src/main/java/com/justdo/fruitfruit/controller/UserController.java
- src/main/java/com/justdo/fruitfruit/model/dao/CompanyMapper.java
- src/main/java/com/justdo/fruitfruit/model/dto/CompanyDTO.java
- src/main/java/com/justdo/fruitfruit/model/service/CompanyService.java
- src/main/java/com/justdo/fruitfruit/view/CompanyResultMessage.java
- src/main/java/com/justdo/fruitfruit/view/UserMenu.java
- src/main/resources/config/mybatis-config.xml
- src/main/resources/sql/user/CompanyMapper.xml
- src/main/resources/sql/user/UserMapper.xml
로그인시 권한에 따라서 해당하는 사용자뷰로 이동하게 수정하였습니다.
company파일들의 경우 아직 개발중입니다.
> #42 Fix: 로그인 기능 수정

- src/main/java/com/justdo/fruitfruit/model/service/WarehouseService.java
- src/main/java/com/justdo/fruitfruit/view/WarehouseMenu.java
- src/main/resources/sql/warehouse/WarehouseMapper.xml
전체 / 판매자아이디 / 상품명으로 재고조회하는 기능 개발완료
> Feature : #20 상품명으로 재고조회 기능 완료

- src/main/java/com/justdo/fruitfruit/controller/CompanyController.java
- src/main/java/com/justdo/fruitfruit/controller/UserController.java
- src/main/java/com/justdo/fruitfruit/model/dao/CompanyMapper.java
- src/main/java/com/justdo/fruitfruit/model/service/CompanyService.java
- src/main/java/com/justdo/fruitfruit/view/UserMenu.java
- src/main/resources/config/mybatis-config.xml
- src/main/resources/sql/user/CompanyMapper.xml
- src/main/resources/sql/user/UserMapper.xml
변경 등록할 정보 입력 받기
입력 받은 데이터  company 테이블에 저장
담당자번호(userSeq)가 이미 등록되어있으면 "이미 판매자 전환이 신청되어 승인대기중 또는 판매자등록이 완료된 계정입니다."를 출력
> Feature : #41 판매자 전환 기능 완료

- src/main/java/com/justdo/fruitfruit/controller/ProductController.java
- src/main/java/com/justdo/fruitfruit/controller/UserController.java
- src/main/java/com/justdo/fruitfruit/model/dao/ProductMapper.java
- src/main/java/com/justdo/fruitfruit/model/dto/ProductDTO.java
- src/main/java/com/justdo/fruitfruit/model/service/ProductService.java
- src/main/java/com/justdo/fruitfruit/view/SellerMenu.java
- src/main/java/com/justdo/fruitfruit/view/UserMenu.java
- src/main/resources/sql/seller/ProductMapper.xml
> #15 Fix : 판매자 로그인 후 버그 수정

- src/main/java/com/justdo/fruitfruit/controller/ProductController.java
- src/main/java/com/justdo/fruitfruit/view/SellerMenu.java
- src/main/resources/config/mybatis-config.xml
- src/main/resources/sql/seller/ProductMapper.xml
> #15 Fix : 판매자 물품 수정, 삭제 버그 수정

- src/main/java/com/justdo/fruitfruit/controller/UserController.java
- src/main/java/com/justdo/fruitfruit/model/dao/UserMapper.java
- src/main/java/com/justdo/fruitfruit/model/service/UserService.java
- src/main/java/com/justdo/fruitfruit/view/MainMenu.java
- src/main/java/com/justdo/fruitfruit/view/UserMenu.java
- src/main/resources/config/mybatis-config.xml
- src/main/resources/sql/user/UserMapper.xml
회원아이디를 찾을 회원 정보 입력 받기(이름, 핸드폰번호)
입력 받은 데이터를 갖고있는 유저의 id 출력
> Feature :#49 회원아이디 찾기 기능 완료

- src/main/java/com/justdo/fruitfruit/view/UserMenu.java
회원가입시 규정에 맞지 않는 비밀번호 설정을 허가하지 않는다.
> #52 feat : 회원가입 비밀번호 정규식 조건 설정

- src/main/java/com/justdo/fruitfruit/controller/UserController.java
- src/main/java/com/justdo/fruitfruit/model/dao/UserMapper.java
- src/main/java/com/justdo/fruitfruit/model/service/UserService.java
- src/main/java/com/justdo/fruitfruit/view/MainMenu.java
- src/main/java/com/justdo/fruitfruit/view/UserMenu.java
- src/main/resources/sql/user/UserMapper.xml
Mainview에 아이디 찾기, 비밀번호 찾기 view 추가
판매자 아이디 찾기 기능 추가
> Feature : #49 판매자 아이디 찾기 완성

- src/main/java/com/justdo/fruitfruit/view/UserResultMessage.java
> #15 Fix : 비회원 물품 조회 기능 결과값 수정

- src/main/java/com/justdo/fruitfruit/controller/ProductController.java
- src/main/java/com/justdo/fruitfruit/controller/SystemController.java
- src/main/java/com/justdo/fruitfruit/controller/UserController.java
- src/main/java/com/justdo/fruitfruit/model/dao/SystemMapper.java
- src/main/java/com/justdo/fruitfruit/model/service/SystemService.java
- src/main/java/com/justdo/fruitfruit/view/MainMenu.java
- src/main/java/com/justdo/fruitfruit/view/SystemMenu.java
- src/main/java/com/justdo/fruitfruit/view/SystemResultMessage.java
- src/main/resources/config/mybatis-config.xml
- src/main/resources/sql/system/SystemMapper.xml
안녕하세요.
#22 시스템 관리자 회원 관리 메뉴 기능 개발하였습니다.
리뷰 부탁드립니다.
감사합니다.
> #22 Feat: 추가 시스템 관리자 회원 관리 메뉴

- src/main/java/com/justdo/fruitfruit/controller/UserController.java
- src/main/java/com/justdo/fruitfruit/model/dao/UserMapper.java
- src/main/java/com/justdo/fruitfruit/model/service/UserService.java
- src/main/java/com/justdo/fruitfruit/view/MainMenu.java
- src/main/java/com/justdo/fruitfruit/view/UserMenu.java
- src/main/java/com/justdo/fruitfruit/view/UserResultMessage.java
- src/main/resources/sql/user/UserMapper.xml
회원의 아이디, 이름, 핸드폰번호 입력받기
회원정보와 일치하는 회원을 select
일치하는 회원이 있으면 비밀번호재설정(update)를 실행
> Feature : #58 회원 비밀번호 찾기 및 재설정 기능 완료

- src/main/java/com/justdo/fruitfruit/controller/ProductController.java
- src/main/java/com/justdo/fruitfruit/model/dto/ProductDTO.java
> #15 Fix : 물품 진행상황 Enum 활용

- src/main/java/com/justdo/fruitfruit/controller/SystemController.java
- src/main/java/com/justdo/fruitfruit/controller/UserController.java
- src/main/java/com/justdo/fruitfruit/model/dao/SystemMapper.java
- src/main/java/com/justdo/fruitfruit/model/service/SystemService.java
- src/main/java/com/justdo/fruitfruit/view/SystemMenu.java
- src/main/java/com/justdo/fruitfruit/view/SystemResultMessage.java
- src/main/resources/sql/system/SystemMapper.xml
안녕하세요.
#23  시스템 관리자 판매자 관리 메뉴 개발하였습니다.
리뷰 부탁드립니다.
감사합니다.
> #23 [기능] 시스템 관리자 판매자 관리 메뉴 개발

- src/main/java/com/justdo/fruitfruit/common/constant/NotificationType.java
- src/main/java/com/justdo/fruitfruit/controller/WarehouseController.java
- src/main/java/com/justdo/fruitfruit/model/dao/WarehouseMapper.java
- src/main/java/com/justdo/fruitfruit/model/dto/NotificationDTO.java
- src/main/java/com/justdo/fruitfruit/model/dto/ProductDTO.java
- src/main/java/com/justdo/fruitfruit/model/dto/ProductLogDTO.java
- src/main/java/com/justdo/fruitfruit/model/dto/RequestReleaseDTO.java
- src/main/java/com/justdo/fruitfruit/model/service/WarehouseService.java
- src/main/java/com/justdo/fruitfruit/view/WarehouseMenu.java
- src/main/java/com/justdo/fruitfruit/view/WarehouseResultMessage.java
- src/main/resources/config/mybatis-config.xml
- src/main/resources/sql/warehouse/WarehouseMapper.xml
- 재고 부족, 유통기한 지난경우 판매자에게 보낼 알림을 등록
> 창고 관리자 메뉴 기능 개발

- src/main/java/com/justdo/fruitfruit/view/UserResultMessage.java
- src/main/resources/sql/user/ProductMapper.xml
비회원 물품 조회 조건 설정 : 출고 가능 상태 물품만 조회 가능
> #15 Fix : 비회원 물품 조회 조건 설정

- src/main/java/com/justdo/fruitfruit/model/service/UserService.java
- src/main/resources/sql/user/CartMapper.xml
> #68 장바구니 수정

- src/main/java/com/justdo/fruitfruit/model/dto/OrderDTO.java
- src/main/java/com/justdo/fruitfruit/model/dto/ProductDTO.java
- src/main/java/com/justdo/fruitfruit/model/dto/UserDTO.java
- src/main/java/com/justdo/fruitfruit/view/UserMenu.java
안녕하세요.
UserDTO, OrderDTO String 리턴 값 수정하였습니다.
감사합니다.
> 수정 DTO toString

- src/main/java/com/justdo/fruitfruit/model/service/UserService.java
- src/main/java/com/justdo/fruitfruit/view/UserMenu.java
- src/main/resources/sql/user/CartMapper.xml
- src/main/resources/sql/warehouse/WarehouseMapper.xml
> FIX : 통합테스트 케이스 오류 수정
